#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "${YELLOW}Updating flake inputs...${NC}"
nix flake update

echo "${YELLOW}Building and switching...${NC}"
nix run .#build-switch

echo "${YELLOW}Upgrading Homebrew packages...${NC}"
brew upgrade

echo "${YELLOW}Cleaning up...${NC}"
nix run .#clean

echo "${GREEN}System fully updated!${NC}"
